name = "def-api"
main = "index.js"
compatibility_date = "2024-03-18"

[vars]
# 추가적인 환경변수가 필요하다면 여기에 작성합니다.

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "def-archive"

[[d1_databases]]
binding = "DB"
database_name = "def-db"
database_id = "cef76255-ffc8-4219-ba60-87522ca46c3b"
